TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 48
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 2
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: '/cluster/work/cvl/gusingh/pretrained_models/slowfast-kinetics/SLOWFAST_8x8_R50.pkl'
  # CHECKPOINT_TYPE: caffe2
  CHECKPOINT_FILE_PATH: '/cluster/work/cvl/gusingh/pretrained_models/slowfast-mit/SLOWFAST_8x8_R50.pyth'
  CHECKPOINT_TYPE: pytorch
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: True
AVA:
  DETECTION_SCORE_THRESH: 0.1
  FRAME_DIR: ""
  ANNOTATION_DIR: "/cluster/work/cvl/gusingh/data/ava-kinetics/annotations/"
  LABEL_MAP_FILE: "ava_action_list_v2.2_for_activitynet_2019.pbtxt"
  EXCLUSION_FILE: "avakin_val_excluded_timestamps.csv"
  TEST_LISTS: ["val.csv"]
  FULL_TEST_ON_VAL: False
  TRAIN_PREDICT_BOX_LISTS: ["kinetics_train_predicted_boxes_YOLO.csv"]
  TEST_PREDICT_BOX_LISTS: ["kinetics_val_predicted_boxes_YOLO.csv"]
  # TEST_PREDICT_BOX_LISTS: ["kinetics_val.csv"] 
  FRAME_LIST_DIR: "/cluster/work/cvl/gusingh/data/ava-kinetics/annotations/kinetics_frame_lists/"
  TRAIN_GT_BOX_LISTS: ["kinetics_train.csv"]
  GROUNDTRUTH_FILE: "kinetics_val.csv"
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.075
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 15, 20]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 80
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 8
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "/cluster/work/cvl/gusingh/data/ava-kinetics/kinetics/experiments/SLOWFAST_32x2_R50_YOLO_03/"
