TRAIN:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 16    # 8 for 2 GPUs
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: "/home/yiflu/Desktop/checkpoints/kincad22cad1_baseline/checkpoint_epoch_00010.pyth"
  CHECKPOINT_TYPE: pytorch
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: False
AVA:
  CAD1: True
  DETECTION_SCORE_THRESH: 0.8
  FRAME_DIR: "/srv/beegfs02/scratch/da_action/data/new_datasets_may_2022/AAD/trimmed_images_may_18_2022_fps25"
  FRAME_LIST_DIR: "/srv/beegfs02/scratch/da_action/data/datasets_yifan/cad1/frame_lists/"
  ANNOTATION_DIR: "/srv/beegfs02/scratch/da_action/data/datasets_yifan/cad1/annotations/"
  LABEL_MAP_FILE: "cad1_action_list.pbtxt"
  EXCLUSION_FILE: "cad1_val_excluded_timestamps.csv"
  TRAIN_LISTS: ["train_new.csv"]
  TEST_LISTS: ["cad1_all.csv"]
  FULL_TEST_ON_VAL: False
  TRAIN_GT_BOX_LISTS: ["cad1_train_new.csv"]
  TRAIN_PREDICT_BOX_LISTS: []
  GROUNDTRUTH_FILE: "cad1_all.csv"
  TEST_PREDICT_BOX_LISTS: ["cad1_all.csv"]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.025
  WARMUP_START_LR: 0.0025
  COSINE_END_LR: 0.00025
  WARMUP_EPOCHS: 2.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  OPTIMIZING_METHOD: sgd
  MAX_EPOCH: 6
MODEL:
  NUM_CLASSES: 8
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce             # cross_entropy    # bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid                # softmax    # sigmoid
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 2    # 2 for 2 GPUs
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
TENSORBOARD:
  TSNE:
    ENABLE: True
    FEATURE_FILE_NAME: "features_ckp_kincad22cad1_no_uda_cad1_all.npy"
    LABEL_FILE_NAME: "labels_ckp_kincad22cad1_no_uda_cad1_all.npy"
NUM_GPUS: 2    # 2 for 2 GPUs
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "/home/yiflu/Desktop/experiments/CAD1/"