DACS:
  TRAIN_ENABLE: True
  AUGMENTATION_ENABLE: True
  PSEUDO_LABEL_ENABLE: True
  CONSISTENCY_LOSS: 'mse_weighted'
  PSEUDO_TARGETS: 'logits'
  CONSISTENCY_LOSS_WEIGHT: 'threshold_uniform'
  THRESHOLDS: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  THRESHOLD: 0.5
AUX:
  TRAIN_ENABLE: False
  TEST_ENABLE: False
  AUX_TYPE: "none"
  CLASSES: 0
  DATASET: Auxava
  DETECTION_SCORE_THRESH: 0.4
  FRAME_DIR: "/srv/beegfs02/scratch/da_action/data/kinetics/images"         #"/raid/susaha/datasets/ava-kinetics/images"
  FRAME_LIST_DIR: "/srv/beegfs02/scratch/da_action/data/datasets_yifan/kinetics_6_5000_all/frame_lists/"          #"/raid/susaha/datasets/ava-kinetics/annotations/kinetics_frame_lists/"
  ANNOTATION_DIR: "/srv/beegfs02/scratch/da_action/data/datasets_yifan/kinetics_6_5000_all/annotations/"         #"/raid/susaha/datasets/ava-kinetics/annotations/"
  LABEL_MAP_FILE: "kinetics_action_list_v2.2.pbtxt"               #"actions.pbtxt"
  EXCLUSION_FILE: "kinetics_val_excluded_timestamps.csv"
  TRAIN_LISTS: ["train.csv"]
  TEST_LISTS: ["val.csv"]
  FULL_TEST_ON_VAL: False
  TRAIN_GT_BOX_LISTS: ["kinetics_train.csv"]
  TRAIN_PREDICT_BOX_LISTS: []
  GROUNDTRUTH_FILE: "kinetics_val.csv"
  TEST_PREDICT_BOX_LISTS: ["kinetics_val.csv"]
  LOSS_FACTOR: 0.05
  F_CONFUSION: 1000
TRAIN:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 8    # 8 for 2 GPUs
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
  CHECKPOINT_FILE_PATH: ""
  CHECKPOINT_TYPE: pytorch
DATA:
  NUM_FRAMES: 1    #2
  SAMPLING_RATE: 1
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
DETECTION:
  ENABLE: True
  ALIGNED: False
AVA:
  DETECTION_SCORE_THRESH: 0.4
  FRAME_DIR: "/srv/beegfs02/scratch/da_action/data/ava/frames/"
  FRAME_LIST_DIR: "/srv/beegfs02/scratch/da_action/data/datasets_yifan/ava_6_5000_all/frame_lists/"
  ANNOTATION_DIR: "/srv/beegfs02/scratch/da_action/data/datasets_yifan/ava_6_5000_all/annotations/"
  LABEL_MAP_FILE: "ava_action_list_v2.2.pbtxt"
  EXCLUSION_FILE: "ava_val_excluded_timestamps_v2.2.csv"
  TRAIN_LISTS: ["train.csv"]
  TEST_LISTS: ["val.csv"]   # frame list file
  FULL_TEST_ON_VAL: False # dimensionality error in case False
  TRAIN_GT_BOX_LISTS: ["ava_train_v2.2.csv"]
  TRAIN_PREDICT_BOX_LISTS: []
  GROUNDTRUTH_FILE: "ava_val_v2.2.csv"  # ava_val_v2.2_luca.csv
  TEST_PREDICT_BOX_LISTS: ["ava_val_v2.2.csv"] # ava_val_predicted_boxes_luca.csv
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0125
  COSINE_END_LR: 0.0005
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  OPTIMIZING_METHOD: sgd
  MAX_EPOCH: 4
MODEL:
  ARCH: 'c2d'
  NUM_CLASSES: 6
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy        # bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: softmax                    # sigmoid
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 4    # 2 for 2 GPUs
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 4   # 2 for 2 GPUs
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "/home/yiflu/Desktop/experiments/AVA2KIN/"